[package]
authors = ["Gamunu Balagalla <gamunu@fastcode.io>"]
name = "blink"
version = "1.0.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
panic-halt = "0.2.0"
ufmt = "0.2.0"
nb = "1.1.0"
embedded-hal = "0.2.7"
pwm-pca9685 = "0.3.1"
infrared = "0.14.2"

[dependencies.arduino-hal]
git = "https://github.com/rahix/avr-hal"
rev = "e0b0105b11a7c4209fb1704276a7921c3139d5cb"
features = ["arduino-uno"]

# this lets you use `cargo fix`!
[[bin]]
name = "blink"
test = false
bench = false

[profile.dev]
panic = "abort"
lto = true
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
debug = true
lto = true
opt-level = "s"
